- name: Ensure localisation files for '{{ bbb_system_locale }}' are available
  locale_gen:
    name: "{{ bbb_system_locale }}"
    state: present

- name: Get current locale and language configuration
  command: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ bbb_system_locale }}'
  command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ bbb_system_locale }}
  changed_when: locale_lang != config_system_locale or locale_language != bbb_system_locale
