---
- name: Install required packages
  apt:
    name: "{{ bbb_required_packages }}"
    update_cache: true
    state: "{{ bbb_state }}"

- name: set version of java to use
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton

- import_tasks: locale.yml

- import_tasks: repositories.yml

- name: install bbb and dependencies
  apt:
    name:
    - mongodb-org
    - bbb-check
    - bbb-html5
    - bigbluebutton
    state: "{{ bbb_state }}"

# nojournal not supported for default engine
# inMemory engine seems only in Enterprise distribution
- name: Ensure mongodb4+ does not use nojournal - systemd
  replace:
    dest: /etc/systemd/system/mongod.service
    regexp: ' --nojournal$'
    replace: ''
    backup: yes
  when: mongodb_version is defined and mongodb_version|string == '4.2'
  notify:
    - reload systemd
    - restart mongo

- name: Ensure mongodb4+ does not use nojournal - config
  template:
    src: mongo4-ramdisk.conf.j2
    dest: /usr/share/meteor/bundle/mongo-ramdisk.conf
    backup: yes
    mode: '0644'
  notify:
    - restart mongo
  when: mongodb_version is defined and mongodb_version|string == '4.2'

- name: LXD | disable freeswitch scheduling options
  replace:
    dest: /lib/systemd/system/freeswitch.service
    regexp: "{{ item.re }}"
    replace: "{{ item.rep }}"
    backup: yes
    mode: '0644'
  with_items:
    - { re: '^IOSchedulingClass=realtime', rep: '#IOSchedulingClass=realtime' }
    - { re: '^CPUSchedulingPolicy=rr', rep: '#CPUSchedulingPolicy=rr' }
  notify:
    - reload systemd

- meta: flush_handlers

- name: Ensure services are enabled
  service:
    name: mongod
    enabled: true
    state: started

- name: Check if bbb_ssl_cert exists
  stat:
    path: "{{ bbb_ssl_cert }}"
  register: bbbcert

- import_tasks: letsencrypt.yml
  when: bbb_letsencrypt_enable and not bbbcert.stat.exists

- import_tasks: certificate-selfsigned.yml
  when: not bbb_letsencrypt_enable and not bbbcert.stat.exists

- import_tasks: config.yml

- import_tasks: coturn.yml
  when: bbb_coturn_enable

- import_tasks: greenlight.yml
  when: bbb_greenlight_enable
