---
- name: add BigBlueButton apt key
  apt_key:
    url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
    id: '{{ bbb_apt_key }}'
    state: present

- name: add multiverse apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }} multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }} multiverse"
    - "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-updates multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release | lower }}-updates multiverse"

- name: add mongodb apt key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version | default('3.4') }}.asc"
    state: present

- name: add Xenial dependency apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  when: ansible_distribution_release == 'xenial'
  with_items:
    - ppa:bigbluebutton/support
    - ppa:rmescandon/yq

- name: add dependency apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu/{{ ansible_distribution_release | lower }}/mongodb-org/{{ mongodb_version | default('3.4') }} multiverse"
    - "deb https://ubuntu.bigbluebutton.org/xenial-22/ bigbluebutton-xenial main"
