---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart bigbluebutton
  command: bbb-conf --restart
  become: yes

- name: restart freeswitch
  systemd:
    state: restarted
    daemon_reload: yes
    name: freeswitch
