---
- name: Converge
  hosts: all
  remote_user: root
  vars:
    bbb_hostname: "{{ lookup('dig', ansible_default_ipv4.address + '/PTR')[:-1] }}"
    bbb_coturn_enable: false
    bbb_coturn_secret: 5a124e7d23631788cb6ede41a60bdb41
    bbb_greenlight_secret: 93e74e44d3252c780477cd234c84a75c
    bbb_greenlight_db_password: 55f8a77fd721769d6aea8039f90cc1c6

    # for testing disable dhparam
    bbb_nginx_dh: false
  roles:
    - "{{ playbook_dir }}/../../"
