---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: hetznercloud
lint: |
  set -e
  yamllint .
  ansible-lint -x 204,306
  flake8
platforms:
  - name: instance
    server_type: cx21
    image: ubuntu-16.04
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 3
scenario:
  name: default
verifier:
  name: ansible
